export const UPDATE_BOARDS = 'UPDATE_BOARDS';
// export const FETCH_BOARDS_START = 'FETCH_BOARDS_START';
// export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS';
// export const FETCH_BOARDS_FAIL = 'FETCH_BOARDS_FAIL';

export const ADD_BOARD_START = 'ADD_BOARD_START';
export const ADD_BOARD_SUCCES = 'ADD_BOARD_SUCCES';
export const ADD_BOARD_FAIL = 'ADD_BOARD_FAIL';

export const REMOVE_BOARD_SUCCES = 'REMOVE_BOARD_SUCCES';
export const REMOVE_BOARD_FAIL = 'REMOVE_BOARD_FAIL';

export const FETCH_LISTS_START = 'FETCH_LISTS_START';
export const FETCH_LISTS_SUCCES = 'FETCH_LISTS_SUCCES';
export const FETCH_LISTS_FAIL = 'FETCH_LISTS_FAIL';

export const FETCH_CARDS_START = 'FETCH_CARDS_START';
export const FETCH_CARDS_SUCCES = 'FETCH_CARDS_SUCCES';
export const FETCH_CARDS_FAIL = 'FETCH_CARDS_FAIL';
