export const FETCH_BOARDS_START = 'FETCH_BOARDS_START';
export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS';
export const FETCH_BOARDS_FAIL = 'FETCH_BOARDS_FAIL';

export const ADD_BOARD_START = 'ADD_BOARD_START';
export const ADD_BOARD_SUCCES = 'ADD_BOARD_SUCCES';
export const ADD_BOARD_FAIL = 'ADD_BOARD_FAIL';
